### ISSUE TITLE
export helper types

### ISSUE THREAD

**Issue by hworld** [snaptopixel/vuex-ts-decorators#11]
Curious what you think about providing helper types for TypedDispatch and TypedCommit instead of the user manually having to declare?

```typescript
export type VuexDispatch<P> = <T extends keyof P>( type: T, value?: P[T] ) => Promise<any[]>;
export type VuexCommit<P> = <T extends keyof P>( type: T, value?: P[T] ) => void;
```
They could then use like so without having to define the whole signature.

```typescript
export class Store
{
	dispatch: VuexDispatch<Actions>;
	commit: VuexCommit<Mutations>;
}
```

**Comment by snaptopixel** [comment]
👍  @hworld will do

**Comment by snaptopixel** [comment]
Actually after implementing this I remembered why I hadn't done it... using helpers in that way kills code-completion in VSCode (type checking still works)

**Comment by hworld** [comment]
ah, yeah, I noticed the same. silly vs code. =]

**Comment by snaptopixel** [comment]
@hworld somehow it is actually working now, weird, but good ;)

I've started a branch for the upcoming refactor will publish soon. Thanks for the interest!
