### ISSUE TITLE
Rewrite

### ISSUE THREAD

**Issue by hworld** [snaptopixel/vuex-ts-decorators#13]
Hey there, I found this library a few days ago, tried implementing it, found a few random bugs and noticed you were working on a rewrite. In the mean time I've actually rewritten it using yours as a base to fix the bugs I noticed.

I figured I'd share what I have so you can take a look and see if anything could work for your rewrite.

All the code for it is in this single file here: https://github.com/gamejolt/frontend-lib/blob/more-rewrites/utils/vuex.ts

I really liked what you were doing with the scopes for the getters, actions, and mutations that you would bind as `this`. I ran into a few problems with that, though.

The first was that it was creating the scope each time the func was called, so I ended up caching it (in a kind of ugly way) to reduce the amount of work that happens in subsequent calls.

The second is that I ran into issues with getters not able to call other getters and actions not able to call a mutation and then check on the value that was mutated after the commit. This was because you were freezing the values of the state into the scope/context object which got rid of the reactivity. When the commit took place and modified the value it didn't update the scope/context object that was passed into the action.

I also figured it could be cool to enforce the scopes a bit by throwing errors when trying to do things you shouldn't: modifying state in an action, dispatching an action within a mutation, etc.

Note that my code only works with namespaced modules and the root store object. It doesn't support modules that aren't namespaced. I'm kind of thinking that with Typescript it may be better to just extend other Stores to sort of mixin the functionality of modules, but I haven't tried tackling just this yet.

You can see a few examples of how I set up stores with this and use it in these:
- main store: https://github.com/gamejolt/gamejolt/blob/more-rewrites/src/app/store/index.ts
- namespaced module pulled into main store: https://github.com/gamejolt/gamejolt/blob/more-rewrites/src/app/store/library.ts

I'm using https://github.com/ktsn/vuex-class to map the state, getters, actions and mutations into components for use. You can see how I use that in these:
- communicating with main store: https://github.com/gamejolt/gamejolt/blob/more-rewrites/src/app/components/shell/shell.ts
- communicating with namespaced stores: https://github.com/gamejolt/gamejolt/blob/more-rewrites/src/app/components/shell/sidebar/sidebar.ts

Not sure if you like this way of doing things or how you envisioned it working. I wouldn't mind helping out on the project if you'd like, though. Also not sure how much time you had to get things working in this project and refactored.

Anyway, I'll close this right after submitting so that it doesn't muddy up the issue list, but hope it helps!

**Comment by hworld** [comment]
I actually forgot another thing I did. I set up the Action scope to have action/mutation functions on the scope but wrap the dispatch/commit methods of the store. This way you don't have to call `this.commit` or `this.dispatch` in the store. Simply calling the methods of the store object will actually do the dispatches and commits for you. I think the added convenience of calling methods like that is really great. =]

**Comment by snaptopixel** [comment]
Awesome @hworld thanks for all of the effort and feedback. I'm excited to take a look, will do soon!

**Comment by Shepless** [comment]
@snaptopixel hey bud, didnt want to create a new issue for this. How is the rewrite coming along? Really keen to start using this in our project at work!

**Comment by snaptopixel** [comment]
Hi @Shepless, thanks for reaching out! I'm not yet using Vue/Vuex day to day so it's hard to find time. I am working on it though, just slowly 🐢
